export interface SlackNotificationData {
  serviceName: string
  severity: 'P0' | 'P1' | 'P2'
  status: 'OPEN' | 'RESOLVED'
  duration: string
  summary: string
  impactMetrics: {
    failureRate: string
    affectedUsers: string
    downtime: string
  }
  actionItems: {
    task: string
    owner: string
    completed: boolean
  }[]
  incidentId: string
}

export async function sendPostmortemToSlack(
  data: SlackNotificationData,
  webhookUrl: string  // ← passed in, not read from env
): Promise<void> {
  const frontendUrl = process.env.FRONTEND_URL || 'http://localhost:5173'

  if (!webhookUrl) {
    throw new Error('Slack webhook URL is not configured')
  }

  const severityEmoji = {
    P0: '🔴',
    P1: '🟠',
    P2: '🟡',
  }[data.severity]

  const truncatedSummary = data.summary.length > 300
    ? data.summary.substring(0, 300) + '...'
    : data.summary

  const actionItemsText = data.actionItems
    .slice(0, 3)
    .map(item => `• ${item.task} — Owner: ${item.owner}`)
    .join('\n')

  const message = {
    blocks: [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: `${severityEmoji} New Postmortem — ${data.serviceName}`,
        },
      },
      {
        type: 'section',
        fields: [
          { type: 'mrkdwn', text: `*Service:*\n${data.serviceName}` },
          { type: 'mrkdwn', text: `*Severity:*\n${data.severity}` },
          { type: 'mrkdwn', text: `*Duration:*\n${data.duration}` },
          { type: 'mrkdwn', text: `*Status:*\n${data.status}` },
        ],
      },
      { type: 'divider' },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*📋 Summary*\n${truncatedSummary}`,
        },
      },
      {
        type: 'section',
        fields: [
          { type: 'mrkdwn', text: `*Failure Rate:*\n${data.impactMetrics.failureRate}` },
          { type: 'mrkdwn', text: `*Affected Users:*\n${data.impactMetrics.affectedUsers}` },
          { type: 'mrkdwn', text: `*Downtime:*\n${data.impactMetrics.downtime}` },
        ],
      },
      ...(actionItemsText ? [
        { type: 'divider' },
        {
          type: 'section',
          text: {
            type: 'mrkdwn',
            text: `*⚡ Action Items*\n${actionItemsText}`,
          },
        },
      ] : []),
      { type: 'divider' },
      {
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: `Generated by PostmortemAI • <${frontendUrl}/incidents/${data.incidentId}|View Full Postmortem>`,
          },
        ],
      },
    ],
  }

  const response = await fetch(webhookUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(message),
  })

  if (!response.ok) {
    throw new Error(`Slack API error: ${response.status} ${response.statusText}`)
  }
}